extends:
  - standard
  - plugin:react/recommended
  - prettier # ←追加
plugins:
  - react
  - prettier # ←追加
rules:
  react/prop-types:
    - 0
  # ↓追加
  prettier/prettier:
    - error
  # ↑追加
settings:
  react:
    version: 16.6 # お使いのReactのバージョン
